# Generated by Django 5.2 on 2025-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('alquiler', 'Alquiler')], default='agregar', max_length=10),
            preserve_default=False,
        ),
    ]
